version: "3"
name: "optysys"
services:
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./var/redis/optysys:/data/cache

    backend:
        build:
            dockerfile: Dockerfile.prod
            context: ./backend
        container_name: backend
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        environment:
            - REDIS_HOST=redis
        depends_on:
            - redis

    frontend:
        build:
            dockerfile: Dockerfile.prod
            context: ./frontend
        container_name: frontend
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
        depends_on:
            - redis
            - backend
