version: "3"
name: "optysys"
services:
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./var/redis/optysys:/data/cache

    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./
        container_name: api
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        environment:
            - REDIS_HOST=redis
        depends_on:
            - redis
