name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join us on [Twitter](https://twitter.com/hitesh22rana).
        Feel free to check out other awesome repositories by **Hitesh Rana** [here](hhttps://github.com/hitesh22rana?tab=repositories&q=&type=source&language=&sort=).
